"""init table

Revision ID: 131f5dc58399
Revises: c0b048f1bbd8
Create Date: 2023-07-03 08:52:47.472228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131f5dc58399'
down_revision = 'c0b048f1bbd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'count_subs',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'count_subs',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###
