"""initial table

Revision ID: 66e8a9c9227c
Revises: 2263146f4498
Create Date: 2023-06-06 23:59:53.405318

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '66e8a9c9227c'
down_revision = '2263146f4498'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('months', sa.SmallInteger(), nullable=True))
    op.alter_column('services', 'service_id',
                    existing_type=sa.INTEGER(),
                    nullable=True,
                    autoincrement=True)
    op.alter_column('users', 'user_id',
                    existing_type=sa.BIGINT(),
                    nullable=True,
                    autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_id',
                    existing_type=sa.BIGINT(),
                    nullable=False,
                    autoincrement=True)
    op.alter_column('services', 'service_id',
                    existing_type=sa.INTEGER(),
                    nullable=False,
                    autoincrement=True)
    op.drop_column('services', 'months')
    # ### end Alembic commands ###
