"""init

Revision ID: 8ad4bfd6d64c
Revises: 3ce5f8f7505d
Create Date: 2023-07-09 21:54:58.631560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad4bfd6d64c'
down_revision = '3ce5f8f7505d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)
    op.alter_column('users', 'count_subs',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'count_subs',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###
