"""init

Revision ID: c0b048f1bbd8
Revises: 9fd67a99519d
Create Date: 2023-06-25 08:50:28.166754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b048f1bbd8'
down_revision = '9fd67a99519d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###
