"""first

Revision ID: 1b0b5690251e
Revises: 
Create Date: 2023-07-30 22:42:41.779595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0b5690251e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('count_subs', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('months', sa.SmallInteger(), nullable=False),
    sa.Column('reminder', sa.DateTime(), nullable=False),
    sa.Column('service_fk', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['service_fk'], ['users.user_id'], name=op.f('fk_services_service_fk_users')),
    sa.PrimaryKeyConstraint('service_id', name=op.f('pk_services'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('users')
    # ### end Alembic commands ###
