"""second

Revision ID: 54b800277f6e
Revises: e477a57198a5
Create Date: 2023-07-30 12:17:49.114567

"""


# revision identifiers, used by Alembic.
revision = '54b800277f6e'
down_revision = 'e477a57198a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
