"""third

Revision ID: 8755eac32318
Revises: 909174c433c5
Create Date: 2023-08-20 11:53:12.779380
"""


# revision identifiers, used by Alembic.
revision = '8755eac32318'
down_revision = '909174c433c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
