"""second

Revision ID: 909174c433c5
Revises: db436374b13e
Create Date: 2023-08-20 11:28:50.008342
"""


# revision identifiers, used by Alembic.
revision = '909174c433c5'
down_revision = 'db436374b13e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
