"""seconddf

Revision ID: daa14d4ab925
Revises: 54b800277f6e
Create Date: 2023-07-30 12:34:01.660266

"""


# revision identifiers, used by Alembic.
revision = 'daa14d4ab925'
down_revision = '54b800277f6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
