"""first

Revision ID: e477a57198a5
Revises: 
Create Date: 2023-07-30 11:53:25.106121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e477a57198a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_name', sa.String(length=32), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('count_subs', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_table('services',
    sa.Column('service_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('months', sa.SmallInteger(), nullable=False),
    sa.Column('reminder', sa.DateTime(), nullable=False),
    sa.Column('service_by_user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(
        ['service_by_user_id'], ['users.user_id'], name=op.f('fk_services_service_by_user_id_users')
    ),
    sa.PrimaryKeyConstraint('service_id', name=op.f('pk_services'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services')
    op.drop_table('users')
    # ### end Alembic commands ###
